language: ruby
rvm:
  - 2.0.0-p247

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: bundle install --without production
script: bundle exec rake db:migrate
script: bundle exec rake db:test:prepare
script: bundle exec rspec spec/