language: ruby
rvm:
  - 2.0.0-p247

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script: 
  - bundle install --without production
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/